<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7091" started-at="2019-03-14T11:15:23Z" finished-at="2019-03-14T11:15:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7091" started-at="2019-03-14T11:15:23Z" finished-at="2019-03-14T11:15:31Z">
      <class name="testscripts.APIScenario">
        <test-method status="PASS" signature="setUpTestSuite(org.testng.ITestContext)[pri:0, instance:testscripts.APIScenario@1500955a]" name="setUpTestSuite" is-config="true" duration-ms="316" started-at="2019-03-14T11:15:23Z" finished-at="2019-03-14T11:15:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@77eb5790]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestSuite -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.APIScenario@1500955a]" name="setUpTestRunner" is-config="true" duration-ms="0" started-at="2019-03-14T11:15:24Z" finished-at="2019-03-14T11:15:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="FAIL" signature="temparatureConvertion_SOAP(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:0, instance:testscripts.APIScenario@1500955a]" name="temparatureConvertion_SOAP" duration-ms="1582" started-at="2019-03-14T11:15:24Z" data-provider="API" finished-at="2019-03-14T11:15:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@6ce139a4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[D:\Miscellaneous_Classic\EndPointInputs\FtoC_Input.xml (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: D:\Miscellaneous_Classic\EndPointInputs\FtoC_Input.xml (The system cannot find the path specified)
at org.testng.Assert.fail(Assert.java:96)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:115)
at testscripts.APIScenario.temparatureConvertion_SOAP(APIScenario.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- temparatureConvertion_SOAP -->
        <test-method status="PASS" signature="setUpTestRunner()[pri:0, instance:testscripts.APIScenario@1500955a]" name="setUpTestRunner" is-config="true" duration-ms="1" started-at="2019-03-14T11:15:25Z" finished-at="2019-03-14T11:15:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestRunner -->
        <test-method status="FAIL" signature="validateUserData_REST(com.cognizant.framework.selenium.SeleniumTestParameters)[pri:0, instance:testscripts.APIScenario@1500955a]" name="validateUserData_REST" duration-ms="5481" started-at="2019-03-14T11:15:25Z" data-provider="API" finished-at="2019-03-14T11:15:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cognizant.framework.selenium.SeleniumTestParameters@6337c201]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[https://reqres.in/api/users; http://ergast.com/api/f1/2017/circuits.json; null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: https://reqres.in/api/users; http://ergast.com/api/f1/2017/circuits.json; null
at org.testng.Assert.fail(Assert.java:96)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:115)
at testscripts.APIScenario.validateUserData_REST(APIScenario.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserData_REST -->
        <test-method status="PASS" signature="tearDownTestSuite()[pri:0, instance:testscripts.APIScenario@1500955a]" name="tearDownTestSuite" is-config="true" duration-ms="429" started-at="2019-03-14T11:15:31Z" finished-at="2019-03-14T11:15:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTestSuite -->
      </class> <!-- testscripts.APIScenario -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
